### ISSUE TITLE
When running script under IPython, it seems like cgtrc was recognized but debug / backend options were not applied

### ISSUE THREAD

**Issue by dementrock** [joschu/cgt#29] opened 2015-09-19 03:54 UTC

**Comment by neocxi** [comment] 2015-09-22 07:19
In my experience, debug option seems to be applied

**Comment by joschu** [comment] 2015-09-30 21:13
Hi @dementrock, I haven't run into this problem before -- could you explain how I can reproduce it?

**Comment by joschu** [comment] 2015-10-08 17:33
I'm going to close this issue for now.

**Closed by joschu** 2015-10-08 17:33 UTC
